name: Build and deploy Python app to Azure Web App - inventarwebapp-linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C785526663974351A67F6780980DCC0D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_538EB7FD09444DE5B3C06D722220EBD5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73253AE69DE24057A33BB66BCC6C9B2C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: inventarwebapp-linux
          slot-name: Production
          package: backend
          startup-command: "uvicorn main:app --host 0.0.0.0 --port 8000"