name: Build and deploy frontend to Azure Web App - inventarfrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DF400BF6FF59472C9A818353877D1B13 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7F59EA0CE6E94954AA0BDC9F4F7E27C2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AF571E3E742432AAE97BAC7BD55BB72 }}

      - name: Deploy frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: inventarfrontend
          slot-name: Production
          package: frontend
          startup-command: "npm start"