name: Deploy Frontend to Azure Web App - inventarfrontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/main_inventarfrontend.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FRONTEND }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FRONTEND }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FRONTEND }}

      - name: Deploy frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: inventarfrontend
          slot-name: Production
          package: frontend